# Generated by Django 5.2.14 on 2026-05-19 05:54

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("patient", "Patient"), ("agency", "Agency Manager")],
                        db_index=True,
                        default="patient",
                        help_text="Determines access permissions and dashboard views.",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Primary phone number (10 digits).",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional alternate contact number.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="House/Flat No., Street, Landmark.",
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Additional address details.",
                        max_length=255,
                    ),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pincode",
                                message="Pin code must be exactly 6 digits.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "profile_complete",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the user has completed profile setup.",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-date_joined"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_id",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Auto-generated booking ID (e.g., BK-a1b2c3d4).",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("nursing", "Nursing Care"),
                            ("homecare", "Home Care"),
                            ("onetime", "One-Time Service"),
                        ],
                        max_length=20,
                    ),
                ),
                ("patient_name", models.CharField(max_length=200)),
                (
                    "patient_gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "patient_age",
                    models.PositiveIntegerField(
                        help_text="Patient must be at least 16 years old.",
                        validators=[django.core.validators.MinValueValidator(16)],
                    ),
                ),
                ("symptoms", models.TextField(blank=True, default="")),
                ("illnesses", models.TextField(blank=True, default="")),
                ("conditions", models.TextField(blank=True, default="")),
                (
                    "discharge_file",
                    models.FileField(
                        blank=True,
                        default="",
                        help_text="Discharge summary document (PDF, JPG, PNG).",
                        upload_to="discharge_docs/%Y/%m/",
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of days for the service (max 365).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(365),
                        ],
                    ),
                ),
                ("address", models.TextField(help_text="Full service address.")),
                ("city", models.CharField(max_length=100)),
                (
                    "pincode",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_pincode",
                                message="Pin code must be exactly 6 digits.",
                                regex="^\\d{6}$",
                            )
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Contact phone for this booking.",
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_phone",
                                message="Phone number must be exactly 10 digits.",
                                regex="^\\d{10}$",
                            )
                        ],
                    ),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Daily rate before discount.",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Discount percentage (0.10 = 10%).",
                        max_digits=5,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Total before discount.",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Final amount after discount.",
                        max_digits=10,
                    ),
                ),
                (
                    "pricing_tier",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Pricing tier applied: daily, weekly, or monthly.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Under Review"),
                            ("confirmed", "Confirmed"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", help_text="Optional review comment."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        limit_choices_to={"status": "completed"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="core.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")], max_length=10
                    ),
                ),
                (
                    "age",
                    models.PositiveIntegerField(
                        help_text="Staff must be at least 18 years old.",
                        validators=[django.core.validators.MinValueValidator(18)],
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, default="", upload_to="staff_photos/"
                    ),
                ),
                (
                    "specializations",
                    models.JSONField(
                        default=list,
                        help_text='List of specializations, e.g. ["Nursing Care", "Post-Surgery"].',
                    ),
                ),
                (
                    "service_types",
                    models.JSONField(
                        default=list,
                        help_text='Service types this staff can provide, e.g. ["nursing", "onetime"].',
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2, help_text="Rate in INR per day.", max_digits=8
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "available",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether the staff member is available for new bookings.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        help_text="The agency that manages this staff member.",
                        limit_choices_to={"role": "agency"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
                "ordering": ["-rating", "name"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned staff member. Null until staff is matched.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="core.staffprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["status", "created_at"], name="core_bookin_status_b29764_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["patient", "status"], name="core_bookin_patient_c1e8aa_idx"
            ),
        ),
    ]
