# Generated by Django 5.2.14 on 2026-06-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="discharge_file",
            field=models.TextField(
                blank=True, default="", help_text="Base64 encoded discharge document."
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="photo",
            field=models.TextField(
                blank=True, default="", help_text="Base64 encoded profile photo."
            ),
        ),
    ]
