# Generated by Django 5.2.14 on 2026-06-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_booking_discharge_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staffprofile",
            name="agency",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("patient", "Patient")],
                db_index=True,
                default="patient",
                help_text="Determines access permissions and dashboard views.",
                max_length=10,
            ),
        ),
    ]
